### PR TITLE
feat: support toggle focus mode for editor

### PR DESCRIPTION
**Pull request by hyoban**
### <samp>🤖 Generated by Copilot at 1dc922a</samp>

This pull request adds a new feature to the post editor component, which allows users to enter a focus mode that hides some UI elements and provides a distraction-free writing environment. It implements the feature by adding a new toolbar command component, a new URL query parameter, and some conditional rendering logic in the editor, layout, and preview components. It also modifies the CSS class of the preview component to improve its appearance in focus mode.

### <samp>🤖 Generated by Copilot at 1dc922a</samp>

> _Focus mode toggle_
> _`router` changes the query_
> _Autumn leaves the sidebar_

### WHY

When using the web editor to edit a post, the width available for editing is too small.  

### <samp>🤖 Generated by Copilot at 1dc922a</samp>

*  Add focus mode toggle functionality to the post editor toolbar ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-b3d555588db2459136141ec7d6cd26e985591d7f2aedcce717b5758cc1c37977R2), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-b3d555588db2459136141ec7d6cd26e985591d7f2aedcce717b5758cc1c37977R87-R99), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-b3d555588db2459136141ec7d6cd26e985591d7f2aedcce717b5758cc1c37977R131-R138), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-b3d555588db2459136141ec7d6cd26e985591d7f2aedcce717b5758cc1c37977L125-R147), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-4e444bbec16351c6a4ddabf2b9cbb9a2dbcdea65247368637f7ff5e05c8663c2R1-R13), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-76c0235eb39ab131c772a22165dfdd5e72defc3818f7825b63f7f6c0fd603931R13), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-76c0235eb39ab131c772a22165dfdd5e72defc3818f7825b63f7f6c0fd603931R33-R36), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-76c0235eb39ab131c772a22165dfdd5e72defc3818f7825b63f7f6c0fd603931R113))
  * Import custom hooks from `next/navigation` to access and manipulate URL query parameters in `EditorToolbar.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-b3d555588db2459136141ec7d6cd26e985591d7f2aedcce717b5758cc1c37977R2))
  * Define variables and function to store router data and create query strings in `EditorToolbar.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-b3d555588db2459136141ec7d6cd26e985591d7f2aedcce717b5758cc1c37977R87-R99))
  * Pass router data and function as a property to the `execute` function of each toolbar command in `EditorToolbar.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-b3d555588db2459136141ec7d6cd26e985591d7f2aedcce717b5758cc1c37977R131-R138))
  * Add router data and function as dependencies to the `useMemo` hook that memoizes the toolbar commands in `EditorToolbar.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-b3d555588db2459136141ec7d6cd26e985591d7f2aedcce717b5758cc1c37977L125-R147))
  * Define a new toolbar command component for the focus mode toggle in `Focus.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-4e444bbec16351c6a4ddabf2b9cbb9a2dbcdea65247368637f7ff5e05c8663c2R1-R13))
  * Import and add the focus mode toggle component to the list of toolbar commands in `index.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-76c0235eb39ab131c772a22165dfdd5e72defc3818f7825b63f7f6c0fd603931R13))
  * Add a new optional property to the `ICommand` type for the router data and function in `index.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-76c0235eb39ab131c772a22165dfdd5e72defc3818f7825b63f7f6c0fd603931R33-R36))
  * Render the focus mode toggle component in the `EditorToolbar` component in `index.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-76c0235eb39ab131c772a22165dfdd5e72defc3818f7825b63f7f6c0fd603931R113))
* Hide sidebar and extra properties components when focus mode is enabled in the post editor and layout components ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-46d42aecfcde90db54ab62e00c4601540f9e7f4f7219423bebda09b32def6970R60), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-46d42aecfcde90db54ab62e00c4601540f9e7f4f7219423bebda09b32def6970L503-R504), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-998c23e4b923ca2f9f8f76529de0639fb3ce4829b3f9a81b0df40e64b3511d28R40), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-998c23e4b923ca2f9f8f76529de0639fb3ce4829b3f9a81b0df40e64b3511d28L316-R422))
  * Add a new variable `isFocus` to check the `focus` query parameter in `post-editor.tsx` and `layout-component.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-46d42aecfcde90db54ab62e00c4601540f9e7f4f7219423bebda09b32def6970R60), [link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-998c23e4b923ca2f9f8f76529de0639fb3ce4829b3f9a81b0df40e64b3511d28R40))
  * Pass `isFocus` as a prop from the layout component to the post editor component in `layout-component.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-998c23e4b923ca2f9f8f76529de0639fb3ce4829b3f9a81b0df40e64b3511d28R40))
  * Add a condition to the existing logic that renders the `extraProperties` component in the post editor component in `post-editor.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-46d42aecfcde90db54ab62e00c4601540f9e7f4f7219423bebda09b32def6970L503-R504))
  * Add a condition to the existing logic that renders the sidebar component in the layout component in `layout-component.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-998c23e4b923ca2f9f8f76529de0639fb3ce4829b3f9a81b0df40e64b3511d28L316-R422))
* Improve the aesthetics of the preview component in focus mode by changing the CSS class for the overflow behavior in `DualColumnEditor.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/1015/files?diff=unified&w=0#diff-608fc367371bb9d05235bdf68e24d1ba963470ce2f6b58afad36226dfa753b75L256-R256))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by DIYgod** [comment]
Thank you for your awesome contribution. I have a potentially better idea: why not try using the [requestFullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen)? It can offer a more immersive experience.

**Comment by hyoban** [comment]
Sorry, I just didn't know there was this API. hhh. I will modify it immediately.

**Comment by hyoban** [comment]
@DIYgod I've modified the code using requestFullscreen, you can review it again when you have time

**Comment by DIYgod** [comment]
Thanks so much!

**Pull request merged**
