### PR TITLE
feat: more embed support

### PR DESCRIPTION
**Pull request by birdgg**
### <samp>🤖 Generated by Copilot at 321f5b0</samp>

This pull request adds the ability to embed various types of content in the markdown content, such as GitHub repositories, music links, CodeSandbox links, tweets, and YouTube videos. It introduces new dependencies, components, and plugins to achieve this functionality. It also deletes the unused `src/markdown/rehype-tweet.ts` file.

### <samp>🤖 Generated by Copilot at 321f5b0</samp>

> _Oh we're the coders of the sea, and we work with `React`_
> _We embed all kinds of links, with `rehypeEmbed` in fact_
> _We pull the ropes and raise the sails, with `Meting` and `Github`_
> _And we sing this shanty loud and proud, on the count of one, two, three, HUB!_

### WHY
- Add rehypeEmbed plugin to help transforming a link into the embedded version of that link.
- Add youtube, github repo, netease music, codesandbox embed.

### <samp>🤖 Generated by Copilot at 321f5b0</samp>

*  Add new dependencies for displaying GitHub repositories, converting HTML to HAST, and matching paths to patterns ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R31), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R76), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R100), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L205-R208))
*  Update lock file with new and updated entries for the new dependencies and their sub-dependencies ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR4-R6), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR139-R141), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR211-R213), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR1724-R1736), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3925-R3933), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL8608-R8644), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR8650), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR11083-R11086))
*  Add new React components for wrapping `APlayer` with `Meting` and `GithubRepo` with `@birdgg/react-github` ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-fbfcb05687fa9d849e814cb8313398027cf1b3eeec62eae55c93ea657c0ad77dR1-R53), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-c4ca2981d3594546510e142ad30fb4ff0760c84ad34c81710883e8766dd34337R1-R5))
*  Add new utility functions for parsing and fetching music data from various platforms using `Meting` API ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-901cf47ef65af9ead1179c37fecd3f7b8074a616a6735da4e605317ff6d27142R1-R60))
*  Add new transformer objects for embedding CodeSandbox, GitHub, MetingAudio, Tweet, and YouTube links in markdown content using iframes or custom components ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-176d6339def3040792282959a729aff55af7e431f3235ecc66e0bbac7f82c78bR1-R23), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-300acaa3245256bc28f076f928d96ca66e48d78f8cf8fca070910278640f9d54R1-R21), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-045188956df0871bcdfbce11124eb67e4de07aadb4d3dfe5716c36e514f075d0R1-R31), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-565652dcd59d25edcccb98dc630753b69bef1d52b56714ef1c53cd44927d38adR1-R19), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-280946285ba4b51eee01e485018f8f54698a57ce3ffbf251bcf990c551e43905R1-R62))
*  Add new utility functions for generating iframe HTML and checking host and path names ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-778db970fbe15bd507d6756dc7fb647b876db3e51a766ee36562c56b15625eb5R1-R34))
*  Export an array of all the transformer objects ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-e3637a5c2e98e8664cfee1156e9d6085cbf5237a3d74c01b324367680996f397R1-R14))
*  Import the array of transformer objects, the `rehypeEmbed` plugin, and the custom components to the main markdown file ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcR34), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcL40-R43), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcL56-R61))
*  Add the `rehypeEmbed` plugin to the unified processor pipeline and map the custom components to the HTML tags ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcL179-R186), [link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcL228-R238))
*  Implement the `rehypeEmbed` plugin that visits all the anchor tags and replaces them with the HTML returned by the transformer objects ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-bd040d577d240ff4d76d4a76b53516403dd1ec107eab84a930ba828f853f50a8R1-R41))
*  Delete the `rehype-tweet` plugin file as it is no longer needed ([link](https://github.com/Crossbell-Box/xLog/pull/560/files?diff=unified&w=0#diff-5c0c9921602d0f079b638201cb558ea587d566dfd53fc5f4d57b4a850f90fff8))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by birdgg** [comment]
https://github.com/Crossbell-Box/xLog/assets/4584859/3abdbfd8-7690-4104-a14c-82a5f57f319f

**Comment by DIYgod** [comment]
Excellent job! Thank you so much! However, I believe that the built-in meeting feature may not be suitable due to potential legal concerns.

**Comment by birdgg** [comment]
I guess so.I will use official iframe embed then.

**Comment by DIYgod** [comment]
Thanks so much!

**Pull request merged**
