### PR TITLE
perf(a11y): add keyboard navigation support to SiteHeader more action…

### PR DESCRIPTION
**Pull request by SevenOutman**
…s menu

### <samp>🤖 Generated by Copilot at 9bd0571</samp>

This pull request improves the site header component by using a more accessible and functional menu library, extracting a reusable subcomponent, and enhancing the focus visibility of the connect button. The changes affect the files `SiteHeader.tsx`, `UniLink.tsx`, and `ConnectButton.tsx`.

### <samp>🤖 Generated by Copilot at 9bd0571</samp>

> _We're heaving up the `SiteHeader` with a mighty roar_
> _We're using `Menu` and `MoreActions` to make it soar_
> _We're adding props and classes to the `button` and the `UniLink`_
> _We're sailing on the web with accessibility and style_

### WHY
Friendly to users without access to a working mouse

https://user-images.githubusercontent.com/8225666/235311398-1bf4d3dd-a1bd-4dbc-8c14-c2b52f204ee1.mov

### <samp>🤖 Generated by Copilot at 9bd0571</samp>

*  Replace custom `Menu` component with `@headlessui/react` `Menu` component for better accessibility and functionality ([link](https://github.com/Crossbell-Box/xLog/pull/464/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL16), [link](https://github.com/Crossbell-Box/xLog/pull/464/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL254-R272))
* Extract `MoreActions` component from `SiteHeader` component and use it to render a dropdown menu with `MoreActions.Item` components ([link](https://github.com/Crossbell-Box/xLog/pull/464/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL28-R35), [link](https://github.com/Crossbell-Box/xLog/pull/464/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dR345-R412))
* Export and use `UniLinkProps` type to define props for `UniLink` and `MoreActions.Item` components ([link](https://github.com/Crossbell-Box/xLog/pull/464/files?diff=unified&w=0#diff-2ae3662ff16f14715077b568c76ed9b1c6e055c71ae9d26b0b150bf79ca27e81L3-R3), [link](https://github.com/Crossbell-Box/xLog/pull/464/files?diff=unified&w=0#diff-2ae3662ff16f14715077b568c76ed9b1c6e055c71ae9d26b0b150bf79ca27e81L9-R18), [link](https://github.com/Crossbell-Box/xLog/pull/464/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL28-R35))
* Add focus visibility and accessibility classes to `button` element in `ConnectButton` component ([link](https://github.com/Crossbell-Box/xLog/pull/464/files?diff=unified&w=0#diff-bcff1bcc3cdc6f01659817ebd75808cbbca143eeed52b41ab365fbba64b491f6L242-R242))
* Add `Fragment` import to `ConnectButton` component to avoid extra `div` element ([link](https://github.com/Crossbell-Box/xLog/pull/464/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL5-R15))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by DIYgod** [comment]
Great work! But is it possible to move the toggle logic to the Menu component, so that all the Menus can enjoy such great functionality?

**Comment by SevenOutman** [comment]
> But is it possible to move the toggle logic to the Menu component, so that all the Menus can enjoy such great functionality?

I considered doing so at the beginning. But then I found that `components/ui/Menu` component uses `@floating-ui/react`, which has some overlap with what `@headless-ui/react` is in charge of. My decision was to use `@headless-ui/react` which is designed to be accessible by default.

**Comment by DIYgod** [comment]
> I considered doing so at the beginning. But then I found that `components/ui/Menu` component uses `@floating-ui/react`, which has some overlap with what `@headless-ui/react` is in charge of. I decided to use Headless UI which is designed to be accessible by default, but I'm not sure if it's OK to drop the Floating UI part from Menu component.

This is no problem, feel free to switch to `@headless-ui/react`

**Comment by SevenOutman** [comment]
@DIYgod Menu is updated and ConnectButton is equipped with keyboard navigation now.

**Comment by DIYgod** [comment]
It has some style issues on my computer.

image
image
image

**Comment by SevenOutman** [comment]
> It has some style issues on my computer.

@DIYgod It's fixed now.
image

**Comment by SevenOutman** [comment]
> The font size appears slightly different 🤔

@DIYgod It's fixed now.

**Comment by DIYgod** [comment]
Thanks so much!

**Pull request merged**
