### PR TITLE
feat: tweet embed 

### PR DESCRIPTION
**Pull request by birdgg**
### <samp>🤖 Generated by Copilot at b102f23</samp>

This pull request adds the functionality to render tweets embedded in markdown files using the `react-tweet` package and a custom `Tweet` component. It also adds a custom `rehypeTweet` plugin that transforms the links to tweets in the markdown files into `tweet` elements. These changes affect the `pnpm-lock.yaml`, `package.json`, `src/markdown/index.ts`, `src/components/ui/Tweet.tsx`, and `src/markdown/rehype-tweet.ts` files.

### <samp>🤖 Generated by Copilot at b102f23</samp>

> _Sing, O Muse, of the skillful coder who devised_
> _A clever way to render tweets in markdown files_
> _Using `react-tweet`, a package of great renown_
> _And `Tweet`, a component of his own design_

### WHY
#487 

### <samp>🤖 Generated by Copilot at b102f23</samp>

*  Add `react-tweet` package as a dependency to render tweets embedded in markdown files ([link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R107), [link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR11842-R11855))
*  Lock the version and resolution of `react-tweet` and its dependencies in `pnpm-lock.yaml` ([link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR235-R237), [link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR4424-R4429), [link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR7070-R7076), [link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR12917-R12925))
*  Create `Tweet` component that wraps `react-tweet` and uses `next/image` to optimize tweet images in `src/components/ui/Tweet.tsx` ([link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-0c55794363137c3ebfebd7d1486446879ac1db4246fd21962e7c7e1c02f7ce5eR1-R12))
*  Import `Tweet` component and `rehypeTweet` plugin to `src/markdown/index.ts` ([link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcR35), [link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcR45))
*  Add `rehypeTweet` plugin to the unified pipeline for processing markdown files and map `tweet` elements to `Tweet` component in `renderPageContent` function ([link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcR177), [link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcR227))
*  Create `rehypeTweet` plugin that transforms links to tweets into custom `tweet` elements with tweet id in `src/markdown/rehype-tweet.ts` ([link](https://github.com/Crossbell-Box/xLog/pull/488/files?diff=unified&w=0#diff-5c0c9921602d0f079b638201cb558ea587d566dfd53fc5f4d57b4a850f90fff8R1-R22))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by DIYgod** [comment]
I don't think rendering any Twitter link as a component is a good way, because sometimes we just want to simply put a link. My suggestion is to limit the rendering of components only when there is only one Twitter link in a paragraph, for example.

```md
First paragraph.

https://twitter.com/_xLog/status/1636897375351365634

Second paragraph.
```

This makes me think that the YouTube component can also be done in this way.

**Comment by birdgg** [comment]
> I don't think rendering any Twitter link as a component is a good way, because sometimes we just want to simply put a link. My suggestion is to limit the rendering of components only when there is only one Twitter link in a paragraph, for example.
> 
> ```lisp
> First paragraph.
> 
> https://twitter.com/_xLog/status/1636897375351365634
> 
> Second paragraph.
> ```

So we dont process tweet links when more than one link in paragraph? @DIYgod 
```
First paragraph.

https://twitter.com/_xLog/status/1636897375351365634

https://twitter.com/Bird_Eggegg/status/1654706673876103169?s=20

Second paragraph.
```

**Comment by DIYgod** [comment]
> So we dont process tweet links when more than one link in paragraph? @DIYgod
> 
> ```
> First paragraph.
> 
> https://twitter.com/_xLog/status/1636897375351365634
> 
> https://twitter.com/Bird_Eggegg/status/1654706673876103169?s=20
> 
> Second paragraph.
> ```

Sorry I didn't explain it clearly. Render only if the Twitter link takes up a separate paragraph, and there should be no other elements in the paragraph. Cases like this are also not rendered.

```md
First paragraph.

link https://twitter.com/_xLog/status/1636897375351365634

Second paragraph.
```

**Comment by birdgg** [comment]
Screenshot 2023-05-07 at 17 47 08

**Pull request merged**
