### PR TITLE
feat: introduce `ModalStack` component for declarative modal creation

### PR DESCRIPTION
**Pull request by Innei**
### <samp>🤖 Generated by Copilot at d12cf47</samp>

This pull request introduces a new modal stack logic that allows the app to display and manage multiple modals in a consistent and performant way. It adds a new `ModalStack` component and a `useModalStack` hook that handle the modal stack operations. It also refactors several components that use modals, such as the page editor, the patron button, and the reaction buttons, to use the new modal stack logic. It also adds an `afterLeave` prop to the `Modal` component to execute a callback after the modal is closed.

### <samp>🤖 Generated by Copilot at d12cf47</samp>

> _To show modals with ease and with style_
> _We created a `ModalStack` pile_
> _With a custom hook `useModalStack`_
> _And an `afterLeave` callback_
> _We can manage the modals with a smile_

### WHY

In this Pull Request (PR), I've introduced a significant enhancement to our modal management in the application.

The main changes are:

1. **Addition of ModalStack Component:** I've added the `ModalStack` component, which enables us to create modals in a declarative manner. This approach leads to less coupling, eliminating the need for manual control over the visibility of modals. This also allows for the invocation of encapsulated modals from anywhere, reducing the cognitive load and the volume of code.

2. **Partial Modal Refactoring:** Alongside the new component, I've refactored a portion of the existing modals to align with this new approach.

This implementation should make maintaining and managing modals easier and more efficient in the future.

As always, I appreciate your time in reviewing this new feature and look forward to any feedback or suggestions for further improvements.

See discord discussion https://discord.com/channels/976854077709369424/1097349373257597040/1124015977970020422

### <samp>🤖 Generated by Copilot at d12cf47</samp>

*  Implement a modal stack logic that allows presenting and dismissing modals programmatically using a context and a hook ([link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-b676e41195831c3b2f9a2909ed07d3ded7e89b147a301c311cffd2407e67f233R34), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-b676e41195831c3b2f9a2909ed07d3ded7e89b147a301c311cffd2407e67f233L286-R321), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-bbb6142c7cbfbe0d99f8fa0a0c04e6d3d3f44ed2e25f0a1f7064cdce48a06382R14), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-bbb6142c7cbfbe0d99f8fa0a0c04e6d3d3f44ed2e25f0a1f7064cdce48a06382L87-R91), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-ba6e473e303f34fc5f993e51dd35c54aa19ff3595b4fb0023332e9cc9a579103L3-R3), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-ba6e473e303f34fc5f993e51dd35c54aa19ff3595b4fb0023332e9cc9a579103L33-R31), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-dc83b8c8b24c6289cc57e21506301c2b1b0c5412c91ac8810620a8516bd8a2c9L17-R57), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-f31f89439bdd1fd8da0d01c8e954041860de2aa70748ee59f1c7be0e9380cf46R21), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-f31f89439bdd1fd8da0d01c8e954041860de2aa70748ee59f1c7be0e9380cf46L54-R83), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-b47218fae45a7f9c1acefa37c248cde5c166c606c7c8ab1ca2c7db73798340ecL3-R7), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-b47218fae45a7f9c1acefa37c248cde5c166c606c7c8ab1ca2c7db73798340ecL48-R51), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-0169e5399d2db5fb42387fef4f204e1e0114631057c7883e615d90000782abc5R1-R165))
*  Replace the state variables and conditional rendering of modals with the `present` and `dismiss` functions from the `useModalStack` hook in the `ReactionLike`, `ReactionTip`, `PatronButton`, and `Editor` components ([link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-b676e41195831c3b2f9a2909ed07d3ded7e89b147a301c311cffd2407e67f233L261-R284), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-b676e41195831c3b2f9a2909ed07d3ded7e89b147a301c311cffd2407e67f233L697-L752), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-b676e41195831c3b2f9a2909ed07d3ded7e89b147a301c311cffd2407e67f233R967-R1010), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-ba6e473e303f34fc5f993e51dd35c54aa19ff3595b4fb0023332e9cc9a579103L23-R25), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-dc83b8c8b24c6289cc57e21506301c2b1b0c5412c91ac8810620a8516bd8a2c9L82-R108), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-dc83b8c8b24c6289cc57e21506301c2b1b0c5412c91ac8810620a8516bd8a2c9L127-R153), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-f31f89439bdd1fd8da0d01c8e954041860de2aa70748ee59f1c7be0e9380cf46L35-R36), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-f31f89439bdd1fd8da0d01c8e954041860de2aa70748ee59f1c7be0e9380cf46L72-R96), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-f31f89439bdd1fd8da0d01c8e954041860de2aa70748ee59f1c7be0e9380cf46L170-R194), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-f31f89439bdd1fd8da0d01c8e954041860de2aa70748ee59f1c7be0e9380cf46R208-R298), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-b47218fae45a7f9c1acefa37c248cde5c166c606c7c8ab1ca2c7db73798340ecL35), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-b47218fae45a7f9c1acefa37c248cde5c166c606c7c8ab1ca2c7db73798340ecL114-L119))
*  Define custom components for the content of the modals that use the modal stack logic, such as `LikeModal`, `UnLikeModal`, `PatronModal`, and `PublishedModal` ([link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-b676e41195831c3b2f9a2909ed07d3ded7e89b147a301c311cffd2407e67f233R967-R1010), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-dc83b8c8b24c6289cc57e21506301c2b1b0c5412c91ac8810620a8516bd8a2c9L17-R57), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-dc83b8c8b24c6289cc57e21506301c2b1b0c5412c91ac8810620a8516bd8a2c9L266-R280), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-f31f89439bdd1fd8da0d01c8e954041860de2aa70748ee59f1c7be0e9380cf46R208-R298))
*  Add a new prop called `afterLeave` to the `Modal` component from `~/components/ui/Modal` that is called after the modal has finished its exit transition and is removed from the DOM ([link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-0c04326a03a8a8e00e64e35c3edd62da56cb506f702f2a70b98b525e880eac98L9-R9), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-0c04326a03a8a8e00e64e35c3edd62da56cb506f702f2a70b98b525e880eac98R19), [link](https://github.com/Crossbell-Box/xLog/pull/741/files?diff=unified&w=0#diff-0c04326a03a8a8e00e64e35c3edd62da56cb506f702f2a70b98b525e880eac98L33-R39))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by Innei** [comment]
And alos fix https://discord.com/channels/976854077709369424/1097349373257597040/1126463682080161884.

**Comment by Innei** [comment]
I think we can try to use Jotai to decouple the state between components

**Comment by Innei** [comment]
This `ModalStack` use `React Context` to implement, so nested two providers, Setter and Getter, this ensures that the children will not re-render. 

There is also a version implemented using Jotai and framer motion that looks much more elegant.

The advantage of framer motion is that you don't have to deal with animations when elements unload.

https://github.com/Innei/sprightly/blob/e1b0b57aaea0eec1b695c4f1961297b42b935044/src/providers/root/modal-stack-provider.tsx

**Comment by DIYgod** [comment]
Thanks so much! And Jotai and framer motion sound great. We can give them a try.

**Pull request merged**
