### PR TITLE
feat: encrypt post

### PR DESCRIPTION
**Pull request by Candinya**
### WHAT
add support for encrypted contents and use password to unlock them

### WHY
User may want to share some non-public contents

### HOW
Use AES-CBC encryption + HMAC signature verify

### Progress
- [x] Add web crypto API helper
- [x] Enable encrypt when post note
- [x] Decrypt on note page
- [x] Decrypt on editor page
- [x] Add translations
- [x] Apply password to `values` when unlock in dashboard
- [x] Place password settings into `Advanced Options` (Or it might overwhelm users)
- [x] Fix modal auto-close issue on mobile
- [ ] Delete unwanted attributes when update an encrypted post with no password

### CODE REVIEW

**Comment by Candinya** [comment]
Some screenshots

image
image
image
image

**Comment by Candinya** [comment]
Algorithm here https://github.com/Crossbell-Box/xLog/blob/71b5be2109b72eab6a5b394e5c71c1f9b9543b4d/src/lib/web-crypto.ts

**Comment by Songkeys** [comment]
Do you think it would be beneficial to include a specific field in [note metadata](https://docs.crossbell.io/docs/specs/metadata/note-metadata) to indicate that a note is encrypted and requires a specific decryption method to read?

**Comment by Candinya** [comment]
> Do you think it would be beneficial to include a specific field in [note metadata](https://docs.crossbell.io/docs/specs/metadata/note-metadata) to indicate that a note is encrypted and requires a specific decryption method to read?

Not sure, maybe we can open a community poll?
Or use some more common fields in attributes (like currently we are using `xlog_encrypt_` prefix to identify them, we can use `encrypt_` instead)

**Comment by Songkeys** [comment]
> Or use some more common fields in attributes (like currently we are using xlog_encrypt_ prefix to identify them, we can use encrypt_ instead)

I think a dedicated field like `encryption: "__method_name_str__"` might be better because it allows every ecosystem app to be aware of displaying a decryption screen instead of just for xlog.

> Not sure, maybe we can open a community poll?

Don't know if anyone in the community is interested in this. We can try though.

**Comment by Candinya** [comment]
> I think a dedicated field like encryption: "__method_name_str__" might be better because it allows every ecosystem app to be aware of displaying a decryption screen instead of just for xlog.

And then maybe we can embed the encryption algorithms into SDK for common usages and further maintains?

**Comment by Songkeys** [comment]
>  embed the encryption algorithms into SDK for common usages and further maintains

Yeah. that sounds better to me, if we are confident with this usage (like it's stable enough).

**Comment by DIYgod** [comment]
Is it a good idea to mark the encrypted part and encryption method with specific syntax instead of using a separate field?

**Comment by Songkeys** [comment]
> Is it a good idea to mark the encrypted part and encryption method with specific syntax instead of using a separate field?

Could you give an example? What's the reason behind this?

**Comment by DIYgod** [comment]
> > Is it a good idea to mark the encrypted part and encryption method with specific syntax instead of using a separate field?
> 
> Could you give an example? What's the reason behind this?

It can be more convenient to achieve partial encryption and reduce the number of fields to improve compatibility.

**Comment by Candinya** [comment]
Too many conflicts, let's refractor this after native encryption (from SDK) is done :wink:

**Pull request closed without merging**
