### PR TITLE
perf(a11y): add focus outline to SiteHeader buttons and links

### PR DESCRIPTION
**Pull request by SevenOutman**
### <samp>🤖 Generated by Copilot at 0f91f15</samp>

Enhanced the site header component with better styling and accessibility. Used `padding` and `gap` utilities to adjust the layout, and added a custom `.focus-ring` class to `src/css/tailwind.css` for keyboard navigation.

### <samp>🤖 Generated by Copilot at 0f91f15</samp>

> _Sing, O Muse, of the skillful coder who refined_
> _The header of the site, where the logo and links shine_
> _With padding and gap utilities he made them fit and fair_
> _And added a focus ring, like the halo of a star_

### WHY
Make focused element more recognizable when user is navigating with keyboard.

https://user-images.githubusercontent.com/8225666/235047444-9a982e92-33c0-4b11-909e-7a468b1cf243.mov

### <samp>🤖 Generated by Copilot at 0f91f15</samp>

* Add horizontal padding and improve wrapping for navigation items in the header ([link](https://github.com/Crossbell-Box/xLog/pull/449/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL48-R48), [link](https://github.com/Crossbell-Box/xLog/pull/449/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL338-R338), [link](https://github.com/Crossbell-Box/xLog/pull/449/files?diff=unified&w=0#diff-98c7783466e499ea1ebc74a559ecfc4dada7fbfbc92b9f65c29c09025182ade5R100), [link](https://github.com/Crossbell-Box/xLog/pull/449/files?diff=unified&w=0#diff-98c7783466e499ea1ebc74a559ecfc4dada7fbfbc92b9f65c29c09025182ade5R408-R411))
* Define and use `.focus-ring` utility class for custom outline and ring style on focused elements ([link](https://github.com/Crossbell-Box/xLog/pull/449/files?diff=unified&w=0#diff-98c7783466e499ea1ebc74a559ecfc4dada7fbfbc92b9f65c29c09025182ade5R18-R23), [link](https://github.com/Crossbell-Box/xLog/pull/449/files?diff=unified&w=0#diff-98c7783466e499ea1ebc74a559ecfc4dada7fbfbc92b9f65c29c09025182ade5R100), [link](https://github.com/Crossbell-Box/xLog/pull/449/files?diff=unified&w=0#diff-98c7783466e499ea1ebc74a559ecfc4dada7fbfbc92b9f65c29c09025182ade5R408-R411))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by DIYgod** [comment]
This modification seems to cause the underline to become longer, it should be as long as the text.

image

**Comment by SevenOutman** [comment]
> This modification seems to cause the underline to become longer, it should be as long as the text.

@DIYgod It's fixed now.

**Comment by DIYgod** [comment]
The hover transition has some collapse 🥲

**Comment by SevenOutman** [comment]
> The hover transition has some collapse 🥲

It's fixed now.

**Comment by DIYgod** [comment]
Thanks so much!

**Pull request merged**
