### PR TITLE
feat: switch language on the panel

### PR DESCRIPTION
**Pull request by cloudflypeng**
close https://github.com/Crossbell-Box/xLog/issues/1881

### WHAT

move nameMap to i18n.ts
add Switch Language i18n
add switch language in ConnectButton.tsx

### WHY
when xlog load the new log,
the footer's Switcher is hard to click

### HOW

image

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.
xlog: 0xEA0e450e3F51A413CeFA44Ac8d37cdBEc572F74e
Discord: meanc.

### CODE REVIEW

**Comment by cloudflypeng** [comment]
xlog在我这太卡了,我就测试了两次,可以多试试

**Comment by cloudflypeng** [comment]
> The style of this submenu is too unusual. Could you implement a submenu similar to this one: [mantine.dev/core/menu/#styles-api](https://mantine.dev/core/menu/#styles-api)?

of course, maybe this weekend

**Comment by Innei** [comment]
CleanShot 2024-06-06 at 11  22 52@2x
This interaction might also be good. After you click Language, expand down the options

**Comment by cloudflypeng** [comment]
image
Waiting for me to optimize my code

**Comment by DIYgod** [comment]
Thanks so much!

**Pull request merged**
