### PR TITLE
feat: add splitting editor view control

### PR DESCRIPTION
**Pull request by enpitsuLin**
### <samp>🤖 Generated by Copilot at c5d3bb2</samp>

This pull request adds a preview feature to the `PageEditor` component, allowing users to see how their content will look on different layouts. It also improves the `CodeMirrorEditor` component to support custom class names, making it more flexible and reusable. These changes affect the files `src/app/dashboard/[subdomain]/editor/page.tsx` and `src/components/ui/CodeMirror.tsx`.

### <samp>🤖 Generated by Copilot at c5d3bb2</samp>

> _To preview the page as you edit_
> _You can toggle a state with a click_
> _The `PageEditor` shows_
> _Different layouts it knows_
> _And `CodeMirrorEditor` gets a class trick_

### WHY

implemented #527, also some other changes

### <samp>🤖 Generated by Copilot at c5d3bb2</samp>

* Add a state variable and a button to toggle the preview visibility of the parsed content in the `PageEditor` component ([link](https://github.com/Crossbell-Box/xLog/pull/530/files?diff=unified&w=0#diff-37b78c444c95ad2fc34b5a3632c3f72686c75f24a3a1d5876872d5d0cc08d261R217), [link](https://github.com/Crossbell-Box/xLog/pull/530/files?diff=unified&w=0#diff-37b78c444c95ad2fc34b5a3632c3f72686c75f24a3a1d5876872d5d0cc08d261L618-R683))
* Modify the layout and logic of the `PageEditor` component to show the preview only on the desktop layout or when the button is pressed on the mobile layout ([link](https://github.com/Crossbell-Box/xLog/pull/530/files?diff=unified&w=0#diff-37b78c444c95ad2fc34b5a3632c3f72686c75f24a3a1d5876872d5d0cc08d261L618-R683))
* Import and use the `cn` utility function to conditionally apply class names based on boolean values ([link](https://github.com/Crossbell-Box/xLog/pull/530/files?diff=unified&w=0#diff-abea3d6f52ccf12e87503b823db64594df934a280129d99326a69b9794cfe0a9R26), [link](https://github.com/Crossbell-Box/xLog/pull/530/files?diff=unified&w=0#diff-abea3d6f52ccf12e87503b823db64594df934a280129d99326a69b9794cfe0a9L241-R247))
* Add a new optional prop `className` to the `XLogCodeMirrorEditorProps` interface and the `CodeMirrorEditor` component, which allows passing custom class names to the editor ([link](https://github.com/Crossbell-Box/xLog/pull/530/files?diff=unified&w=0#diff-abea3d6f52ccf12e87503b823db64594df934a280129d99326a69b9794cfe0a9R45), [link](https://github.com/Crossbell-Box/xLog/pull/530/files?diff=unified&w=0#diff-abea3d6f52ccf12e87503b823db64594df934a280129d99326a69b9794cfe0a9L241-R247))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by enpitsuLin** [comment]
## preview
splitting-editor-control

**Comment by DIYgod** [comment]
If the article is long, the button may be located outside of the visible area. 🥲

**Comment by DIYgod** [comment]
If the article is long, the button may be located outside of the visible area. 🥲

**Comment by enpitsuLin** [comment]
I find a little problem, maybe I should refactor the layout for the editor page, draft for now

**Comment by enpitsuLin** [comment]
I think it's fixed now, cc @DIYgod

**Comment by DIYgod** [comment]
The layout is disordered  🥲

image

**Comment by enpitsuLin** [comment]
> The layout is disordered 🥲
> 
> image

cant reproduce in both three browsers on my machine (chrome, chromium edge, firefox)

but also fixed some problems, I think I'm not myself these days 

<details>

<summary>preview</summary>

pc-preview

mobile-preview

</details>

**Comment by DIYgod** [comment]
Thank you so much, but we can use flex to make the style more concise. I have made some modifications here. c3f891e1abcb29aaba1d47c8f235a384babdec49

**Pull request merged**
