### PR TITLE
feat: editor support aplayer

### PR DESCRIPTION
**Pull request by SteveYuOWO**
### <samp>🤖 Generated by Copilot at a81a306</samp>

This pull request adds support for uploading and displaying audio files in the markdown editor using `aplayer`, a web audio player. It introduces a custom `rehypeAudio` plugin for rendering markdown content with `aplayer` components, and uses `node-id3` to handle ID3 tags from audio files. It also updates the dependencies and the IPFS URL parsing logic.

### <samp>🤖 Generated by Copilot at a81a306</samp>

> _We're sailing on the IPFS sea, with `aplayer` on our deck_
> _We parse and convert the audio links, with `ipfs-parser` in our neck_
> _We heave and ho, we heave and ho, we heave and ho on the count of three_
> _We make the markdown sound so sweet, with `rehypeAudio` in our feet_

### WHY
issue #319 #57 

### <samp>🤖 Generated by Copilot at a81a306</samp>

*  Add `aplayer` dependency and types to enable web audio player with custom themes and playlists ([link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R56), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R130), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR91-R93), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR309-R311), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR5366-R5373), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR10683-R10686), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR11764-R11767))
*  Add `node-id3` dependency to read and write ID3 tags from audio files ([link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R81), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR166-R168), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR10008-R10013), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR8177-R8183), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR11531-R11534))
*  Implement custom `rehype` plugin to transform `<audio>` elements into `aplayer` components in markdown rendering pipeline (`src/markdown/rehype-audio.ts`, [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcR12), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-733efe578c40ff2e6b0770350d988ec422a6d3ad9f1543b2bcda58e0ed546fdcR108))
*  Modify markdown editor component to handle audio file upload and insertion with ID3 tags (`src/pages/dashboard/[subdomain]/editor.tsx`, [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-842ea70ef7b4f5946fc6938a7a1eba15216a05a8bd9de0d2963aec6b8e0753c0R47), [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-842ea70ef7b4f5946fc6938a7a1eba15216a05a8bd9de0d2963aec6b8e0753c0L372-R421))
*  Export IPFS prefix constant for reuse in other modules (`src/lib/ipfs-parser.ts`, [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-76ccd7557036cf9272fe991fc0680e5683ed4f925e067b95896543ee85eb1c70L3-R3))
*  Import `aplayer` CSS file to apply global styles to `aplayer` components (`src/pages/_app.tsx`, [link](https://github.com/Crossbell-Box/xLog/pull/349/files?diff=unified&w=0#diff-88a36bc7a53bfa58c6f451464798d631d785160dfacfdaf9479be7a0b1d7e5e5L3-R3))

### CODE REVIEW

**Comment by SteveYuOWO** [comment]
Briefly describe the functions of PR:

1. Drag and drop support for audio files
2. Parsing metadata of audio files
3. Support for APlayer.
image

**Comment by SteveYuOWO** [comment]
Briefly describe the functions of PR:

1. Drag and drop support aplayer for audio files
2. Parsing metadata of audio files
3. Upload audio files & cover
image

**Comment by SteveYuOWO** [comment]
支持过程中遇到一些困难  @DIYgod 

The following error occurs during the build&dev process.
Nextjs is ssr rendering, The issue looks like https://github.com/DIYgod/APlayer/issues/671 . Could there be a way to 'new Aplayer' on the client side?
image

**Comment by Innei** [comment]
> 支持过程中遇到一些困难 @DIYgod
> 
> The following error occurs during the build&dev process. Nextjs is ssr rendering, The issue looks like [DIYgod/APlayer#671](https://github.com/DIYgod/APlayer/issues/671) . Could there be a way to 'new Aplayer' on the client side? image

Aplayer 比较重并不支持 SSR ，可以考虑抽离成 React 组件，然后在 client side lazyload，参考 src/markdown/rehype-mermid.ts 和 src/components/ui/Mermaid.tsx。

https://github.com/Crossbell-Box/xLog/blob/d7a9c1dc1b8d16e82ab69bb7e1a7647f79e7d2ac/src/components/ui/Mermaid.tsx#L16

这里有一个轻量版本的 React Aplayer 或许可以尝试？

**Comment by SteveYuOWO** [comment]
> > 支持过程中遇到一些困难 @DIYgod
> > The following error occurs during the build&dev process. Nextjs is ssr rendering, The issue looks like [DIYgod/APlayer#671](https://github.com/DIYgod/APlayer/issues/671) . Could there be a way to 'new Aplayer' on the client side? image
> 
> Aplayer 比较重并不支持 SSR ，可以考虑抽离成 React 组件，然后在 client side lazyload，参考 src/markdown/rehype-mermid.ts 和 src/components/ui/Mermaid.tsx。
> 
> https://github.com/Crossbell-Box/xLog/blob/d7a9c1dc1b8d16e82ab69bb7e1a7647f79e7d2ac/src/components/ui/Mermaid.tsx#L16-L23
> 
> 这里有一个轻量版本的 React Aplayer 或许可以尝试？
> 
> Refer: https://github.com/SevenOutman/aplayer-react

我看看能不能改成这样

**Comment by SteveYuOWO** [comment]
> > 支持过程中遇到一些困难 @DIYgod
> > The following error occurs during the build&dev process. Nextjs is ssr rendering, The issue looks like [DIYgod/APlayer#671](https://github.com/DIYgod/APlayer/issues/671) . Could there be a way to 'new Aplayer' on the client side? image
> 
> Aplayer 比较重并不支持 SSR ，可以考虑抽离成 React 组件，然后在 client side lazyload，参考 src/markdown/rehype-mermid.ts 和 src/components/ui/Mermaid.tsx。
> 
> https://github.com/Crossbell-Box/xLog/blob/d7a9c1dc1b8d16e82ab69bb7e1a7647f79e7d2ac/src/components/ui/Mermaid.tsx#L16-L23
> 
> 这里有一个轻量版本的 React Aplayer 或许可以尝试？
> 
> Refer: https://github.com/SevenOutman/aplayer-react
我尝试是否可以改成 React Aplayer 。React Aplayer 好像是原生 ts 写的。这样也不需要 d.ts 支持了

**Comment by DIYgod** [comment]
I'm sorry you're doing so much work, but APlayer is very old and has not been maintained for a long time. It is no longer suitable for continued use. I also recommend using [SevenOutman/aplayer-react](https://github.com/SevenOutman/aplayer-react)

**Comment by SteveYuOWO** [comment]
@DIYgod  Replaced with [SevenOutman/aplayer-react](https://github.com/SevenOutman/aplayer-react)

image

This Aplayer is surrounded by a `<p>` tag and generates a warning `warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.` It looks like an issue with the Editor component.

**Pull request merged**
