### PR TITLE
feat: add banner mask

### PR DESCRIPTION
**Pull request by Innei**
### <samp>🤖 Generated by Copilot at cc4f1ab</samp>

Improved the site header component and added a custom CSS rule. The site header now adapts to different screen sizes and has a better visual design. The `overflow: overlay` rule allows customizing the scrollbars for the navigation links.

### <samp>🤖 Generated by Copilot at cc4f1ab</samp>

> _We defy the default configuration_
> _We unleash the custom scrollbars_
> _We mask the overflow with gradient_
> _We adapt the colors of the stars_

### <samp>🤖 Generated by Copilot at cc4f1ab</samp>

*  Prevent horizontal scrolling and overflow issues on small screens by adding `max-w-[100vw]` and `overflow-hidden` classes to the header element ([link](https://github.com/Crossbell-Box/xLog/pull/471/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL181-R181))
* Create a gradient mask effect for the site navigation links by adding `xlog-site-navigation__root` and `xlog-site-navigation__mask` elements ([link](https://github.com/Crossbell-Box/xLog/pull/471/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL337-R345))
* Use a CSS variable `--auto-theme-color` to match the mask color to the average color of the site logo ([link](https://github.com/Crossbell-Box/xLog/pull/471/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL337-R345))
* Extend the mask gradient beyond the viewport edges using pseudo-elements ([link](https://github.com/Crossbell-Box/xLog/pull/471/files?diff=unified&w=0#diff-6e18f36f987fcb1f6f7ccb4a8218939f8069f905afdcb15ee50162c64582674dL337-R345))
* Enable custom scrollbars for the site navigation links by adding `overflow: overlay` rule to the `src/css/tailwind.css` file ([link](https://github.com/Crossbell-Box/xLog/pull/471/files?diff=unified&w=0#diff-98c7783466e499ea1ebc74a559ecfc4dada7fbfbc92b9f65c29c09025182ade5R10))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by DIYgod** [comment]
I think this style modification looks a bit strange on many websites. The background is too prominent, and the center alignment does not match the left-aligned design of the avatar and other information above it. 🥲

**Comment by Innei** [comment]
I change the mask background to shallow gray.

**Comment by Innei** [comment]
Why always redirect to crossbell.app in vercel preview mode?

**Comment by DIYgod** [comment]
I still prefer the simpler style before. But I am preparing the theme system, maybe we can put this style into a theme.

**Comment by Innei** [comment]
> I still prefer the simpler style before. But I am preparing the theme system, maybe we can put this style into a theme.

OK, I will close this pr, my original intention was that the text was not clear due to the background.

**Pull request closed without merging**
