### PR TITLE
feat: more editor shortcuts

### PR DESCRIPTION
**Pull request by daidr**
### <samp>🤖 Generated by Copilot at 63d2da3</samp>

This pull request adds the emoji and mention features to the editor toolbar, and updates the execute functions of the existing commands to accept a consistent parameter type. It also adds the `react-popper` dependency and its transitive dependencies to the project, and updates the URL for fetching the emoji data. Additionally, it adds the translation for the mention label in the Chinese dashboard locale file. These changes improve the editor functionality, type safety, performance, and localization.

### <samp>🤖 Generated by Copilot at 63d2da3</samp>

> _Sing, O Muse, of the skillful coder who devised_
> _Many wondrous commands for the editor of words,_
> _Using `react-popper` and `emoji-mart` as his guides,_
> _And adding the power of mentions and emojis to his lords._

### WHY
shortcuts for mention and emoji picker
image
image

### <samp>🤖 Generated by Copilot at 63d2da3</samp>

*  Add the `react-popper` dependency and its sub-dependencies to the `package.json` and `pnpm-lock.yaml` files ([link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R90), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR193-R195), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3201), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3210), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3219), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3228), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3327), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3337), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3347), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3357), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3459-R3462), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR11171-R11174), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR11262-R11275), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR13510-R13515))
*  Add the `libc` metadata field to the `pnpm-lock.yaml` file for some dependencies that use the C standard library ([link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3201), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3210), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3219), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3228), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3327), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3337), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3347), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3357))
*  Implement the emoji and mention features in the `EditorToolbar.tsx` file by using the `useRef`, `Popover`, and `usePopper` hooks and components, and by rendering a custom UI for the commands that have a `ui` field ([link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-aa80e8c0a1efed4175a1fa0b2c43718ff8824c57f473db17c92b5635e9993edeL3-R8), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-aa80e8c0a1efed4175a1fa0b2c43718ff8824c57f473db17c92b5635e9993edeL20-R74), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-aa80e8c0a1efed4175a1fa0b2c43718ff8824c57f473db17c92b5635e9993edeL33-R84))
*  Define the emoji and mention commands in the `Emoji.tsx` and `Mention.tsx` files, and export them from the `index.tsx` file ([link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-3aa3ffca9093574557774ba6386918f75f0e15f3ee959e879c88103bdf7000dcR1-R14), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-699237e5c5c86c62b2b58810d4f7905dd270c2db2d23f72b2bdbe61efe4aaab4R1-R10), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-7ee6c0a2f0093f8c1f315c4be6d17d4ba350b4de2b9634a73d43db4bd67d939eR140-R141))
*  Modify the `ICommand` type in the `index.tsx` file to accept a generic parameter for the payload, and to change the `execute` function to accept an object with the `view`, `options`, and `payload` properties ([link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-7ee6c0a2f0093f8c1f315c4be6d17d4ba350b4de2b9634a73d43db4bd67d939eL16-R37))
*  Modify the `execute` functions of the other commands in the `Bold.tsx`, `Code.tsx`, `CodeBlock.tsx`, `Heading.tsx`, `Image.tsx`, `Italic.tsx`, `Link.tsx`, `ListOrdered.tsx`, `ListUnordered.tsx`, `Quote.tsx`, `Strikethrough.tsx`, and `Underline.tsx` files to accept an object with the `view` property ([link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-794f034211378eaf3a1cba96dac0d41be1988fe388b9f481258abac287e46d9eL8-R8), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-a37732f83051efebadaf9be347e6635b593f7f9cf8b5e7d8fe2ad767d84cfaf8L8-R8), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-f340f77f01e6dee3af1f828dd0b468098e1f7fb081c47049c65e129d567fa707L7-R7), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-df4a1cf56c8d18960e0816955c52a21836c96dcf8b123d481fad3e2b5037bc7dL7-R7), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-2078cb3b0ae04e39bcf43cb78159816f775e5862dc4814938f0ce5fa8427c9e7L10-R10), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-6b5a0434fedcdd277e64143b322b2d7f7191d5d3a1cac5acc339717854c547ddL7-R7), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-ec2f2827b3d052ac7c7b924838664b1fbad802c08c8fe5930d098f94da73da33L8-R8), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-65db7d384c61d846df6a4d468593b9ebbc90d5c012a2271b38f91b7441d15b27L8-R8), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-cbda5dfe926c8de5dacd2967b6a18b9d5429052a12b0ee659f9738ca3d5ec3c3L7-R7), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-d46fbf3559a975be396cc03d348b975c545a3aa20d21604da3210fae6f50865aL7-R7), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-0faa52ad5a5f01faae99abda7e9b6085b9405abf92791d0670755cd0c270fe4eL7-R7), [link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-ab4ee561a237dce64fde5108aebaeed1664bed5ec5f5d63be1d70036601073dcL7-R7))
*  Add the `input.remove()` statement to the `Image.tsx` file to remove the input element from the DOM after the image upload is completed or failed ([link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-2078cb3b0ae04e39bcf43cb78159816f775e5862dc4814938f0ce5fa8427c9e7R28-R29))
*  Add the translation for the "Mention" label in the Chinese dashboard locale file ([link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-b96cdea1e3b6db8de6ba9473897c4c805f83a25e6b7fef25f339cb2cd95722cbR62))
*  Change the URL for fetching the emoji data in the `EmojiPicker.tsx` file to use a faster and more reliable CDN provider ([link](https://github.com/Crossbell-Box/xLog/pull/338/files?diff=unified&w=0#diff-89d08131aca236077bb39c40adb242cf01fd2872e7cd653f0cfe45c0cbc58400L11-R11))

### CODE REVIEW

**Comment by daidr** [comment]
new dependency `react-popper` was used to get the current position of the popover
https://headlessui.com/react/popover#positioning-the-panel

**Comment by DIYgod** [comment]
It looks like the positioning is not working for me 🤔

image

**Comment by daidr** [comment]
> It looks like the positioning is not working for me 🤔
> 
> image

Might be fixed in https://github.com/Crossbell-Box/xLog/pull/338/commits/734e6d282fa359b1f69e7147a728876c54e5e408.

Also added loading state for EmojiPicker in https://github.com/Crossbell-Box/xLog/pull/338/commits/67c15444c515f61890cd56eb3fe5ab81a44fe392

**Comment by DIYgod** [comment]
Perfect, thank you so much.

**Pull request merged**
