### PR TITLE
Adding social platform Mastodon.World

### PR DESCRIPTION
**Pull request by HelimLee**
### WHAT
Mastodon.world is a decentralized social media platform based upon Mastodon.

### WHY
It's a replacement for Twitter. 

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by 2096779623** [comment]
This can be confusing if there are many social platforms based on Mastodon/Matrix/Misskey.

**Comment by enpitsuLin** [comment]
Mastodon is one of my motivations in #422 

as a decentralized social platform, `mastodon` cannot be easily integrated with `xlog`.

**Comment by HelimLee** [comment]
> Mastodon is one of my motivations in #422
> 
> as a decentralized social platform, `mastodon` cannot be easily integrated with `xlog`.

I think someone should build a "decentralized social network entry" to collect user information and their content's link into one platform to help navigate users.

**Comment by Candinya** [comment]
Actually we have an account standard for decentralized platforms(like mastodon) in this format:

`candinya@thenomads.social`

What about using this rather than specify domains? (parse method might need some updates then)

BTW `.ico` files are not modern anymore, maybe consider use a PNG file for icon instead

**Comment by DIYgod** [comment]
Thank you so much for your contribution, but this has been included in #529, so the PR will be closed.

**Pull request closed without merging**
