### PR TITLE
feat: support self-hosted umami

### PR DESCRIPTION
**Pull request by ImSingee**
### <samp>🤖 Generated by Copilot at 0e3bbd9</samp>

This pull request adds a new feature that allows users to enter a custom URL for the Umami Cloud Analytics script for their sites and characters. It modifies the `GeneralSettingsPage` component, the `updateSite` function, the `SiteFooter` component, the `expandCrossbellCharacter` function, and the `ExpandedCharacter` type to support the feature. It also adds and updates the translation keys and values for the dashboard in the `public/locales` and `src/lib/i18n/locales` folders.

### <samp>🤖 Generated by Copilot at 0e3bbd9</samp>

> _`Umami Cloud Analytics` in your site_
> _Customize the URL or leave it blank_
> _`ExpandedCharacter` with a new trait_
> _`updateSite` function seals your fate_

### WHY

Support the self-hosted version of umami

### <samp>🤖 Generated by Copilot at 0e3bbd9</samp>

*  Add a new state variable, type declaration, and input component for the custom URL for the Umami Cloud Analytics script in the `GeneralSettingsPage` component ([link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-fcdb6dd297ab430ed34aab79585386ccb425672b82314187806ee2af0d9b5245R33), [link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-fcdb6dd297ab430ed34aab79585386ccb425672b82314187806ee2af0d9b5245R44), [link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-fcdb6dd297ab430ed34aab79585386ccb425672b82314187806ee2af0d9b5245L205-R235))
*  Send the user input for the custom URL to the backend in the `updateSite` function call in the `GeneralSettingsPage` component ([link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-fcdb6dd297ab430ed34aab79585386ccb425672b82314187806ee2af0d9b5245R57))
*  Populate the input field with the existing value of the custom URL from the `site` query in the `GeneralSettingsPage` component ([link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-fcdb6dd297ab430ed34aab79585386ccb425672b82314187806ee2af0d9b5245R100-R101))
*  Load the custom URL or the default URL for the Umami Cloud Analytics script in the `SiteFooter` component ([link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-765d257cdb9e99b90862bdf509d92d60910659262e97a25f78e2c48a44847bcfL110-R112))
*  Store the custom URL for the Umami Cloud Analytics script in the `expandedCharacter` object in the `expandCrossbellCharacter` function ([link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-0802612f2ebfab23d2656fc2189271c4fef6451452a2bd7dacc8d8bcfe11e2e8R113-R116))
*  Update the custom URL for the Umami Cloud Analytics script in the database in the `updateSite` function in the `src/models/site.model.ts` file ([link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-8db5e50556c7105744e774aa64e610078c43b9a84d4e2d39bc7fcdaca85d6760R110), [link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-8db5e50556c7105744e774aa64e610078c43b9a84d4e2d39bc7fcdaca85d6760R147), [link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-8db5e50556c7105744e774aa64e610078c43b9a84d4e2d39bc7fcdaca85d6760R182-R189))
*  Add a new optional property for the custom URL to the `ExpandedCharacter` type in the `src/lib/types.ts` file ([link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-b8b77f5be18cf56dca425b3a5b8e9d2e754dd37fe0e3612b95cd4e9bccda08a5R105))
*  Add new translation keys and values for the help text for the input field in the Japanese, Traditional Chinese, and Simplified Chinese locales in the `public/locales` and `src/lib/i18n/locales` folders ([link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-672f3a5746f1d60bb9fa456dd4ddfe70a24c397e436e73001a2114f360b5c635R90), [link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-20d6f7fc6b8cf3a7cd045ffc933ca8457bba669db9007f4c24a8e3ef0d748bb9R95), [link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-b96cdea1e3b6db8de6ba9473897c4c805f83a25e6b7fef25f339cb2cd95722cbR96), [link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-35732bfc6b9d2c778d4e207e3db92728acd62080a69343c11e35e7a49dc4b532R90), [link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-7e65bab74206cf373f8f3034c1de7acdd15ed2fc4b912e47c67a951dc7db01e7R95), [link](https://github.com/Crossbell-Box/xLog/pull/520/files?diff=unified&w=0#diff-3b3413294ac416902eb47e3aa9ac357b0ebb21b46f7ea157940981b0d2f3c977R96))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

xLog bryan

discord Singee#2858

### CODE REVIEW

**Comment by Candinya** [comment]
Custom scripts can be malicious, especially with such a wallet-integrated platform.
Maybe we can find a better method before supporting custom scripts loading.

**Comment by ImSingee** [comment]
@Candinya There do have a method to support this.

```html
<script async defer
  src="https://analytics.umami.is/script.js"
  data-website-id="94db1cb1-74f4-4a40-ad6c-962362670409"
  data-host-url="http://stats.mywebsite.com"
></script>
```

But I do not use it because sometimes the umami is blocked (by GFW or by the browser extension)

**Comment by ImSingee** [comment]
But maybe we can use something like `https://xxx.xlog.app/umami.js`? Since the `umami.js` do not differ between sites.

(Cons: We have to keep track of the upstream script update)

**Comment by DIYgod** [comment]
I prefer to use `https://analytics.umami.is/script.js`. Although xLog can reverse proxy it, it would violate user rights and intentions.

**Comment by ImSingee** [comment]
@Candinya @DIYgod Hi I have updated my code to use the user script (and rebase to the latest dev branch)

**Comment by DIYgod** [comment]
Thank so much!

**Pull request merged**
