### PR TITLE
fix: summary replace neutral subject

### PR DESCRIPTION
**Pull request by Innei**
### <samp>🤖 Generated by Copilot at aad20b1</samp>

Refactor markdown removal and improve summarization prompt for neutral subjects. The file `src/pages/api/summary.ts` uses a new function `stripMarkdown` and modifies the prompt template to avoid biased summaries.

### <samp>🤖 Generated by Copilot at aad20b1</samp>

> _`Refactor` the code, unleash the power_
> _`Utility` function, strip the markdown_
> _`Prompt` template, no more confusion_
> _`Neutral` subjects, face the summarization_

### WHY

If `ta` in zh, don't replace with he, should be they

### <samp>🤖 Generated by Copilot at aad20b1</samp>

*  Strip markdown syntax from input text using `removeMarkdown` function from `./src/utils/removeMarkdown.ts` ([link](https://github.com/Crossbell-Box/xLog/pull/494/files?diff=unified&w=0#diff-0597cc186c7dfa1b87f2525f692d38b0cf0d6d70f0738706fce55e980b6b8ac2R5),[link](https://github.com/Crossbell-Box/xLog/pull/494/files?diff=unified&w=0#diff-0597cc186c7dfa1b87f2525f692d38b0cf0d6d70f0738706fce55e980b6b8ac2L11))
*  Modify prompt template for `getOriginalSummary` function to include clarification for neutral subjects ([link](https://github.com/Crossbell-Box/xLog/pull/494/files?diff=unified&w=0#diff-0597cc186c7dfa1b87f2525f692d38b0cf0d6d70f0738706fce55e980b6b8ac2L37-R37))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by Innei** [comment]
image

**Comment by Songkeys** [comment]
I think asking gpt to use "this author" instead would be better.

**Comment by Innei** [comment]
> I think asking gpt to use "this author" instead would be better.

It doesn't always mean the author, right?

**Comment by Innei** [comment]
There is no update on this PR. Do we still need to follow up on this requirement? @DIYgod @Songkeys

**Comment by DIYgod** [comment]
There doesn't seem to be much difference. Just GPT3.5 did not understand TA very well.

image

Also, may I ask if this modification is to solve this problem?

image

**Comment by Innei** [comment]
CleanShot 2023-06-11 at 10 59 26@2x

Does this feature still need to be followed up on? or should we just adjust Prompt?

**Comment by DIYgod** [comment]
It doesn't seem very important, and I don't want to make the prompt word complicated because of it.

**Pull request closed without merging**
