### PR TITLE
fix: component and state separated, fixed #240

### LINKED ISSUE #240: Delete prompt keeps showing
image

### PR DESCRIPTION
**Pull request by Innei**
This pr fixed #240

### CODE REVIEW

**Comment by DIYgod** [comment]
It seems that the problem still exists. 🥲

image

**Comment by Innei** [comment]
Do you have a reproduction video? I don't seem to have reproduced it on my end.

**Comment by DIYgod** [comment]
I can describe the steps. First, delete a post, and then immediately delete another post while the first one is still in progress. This will result in the second post being displayed as deleted successfully, while the first post continues to display as deleting.

**Comment by DIYgod** [comment]
I'm not sure what the reason is either, but I guess it might be related to data refreshing. 🤔

**Comment by Innei** [comment]
Previously,  setToastId  may have been overwritten, causing the old  toastId  to not be eliminated. Therefore, I extracted  MenuItem , and now each item has an independent state, so there is no problem with overwriting.

There may be other issues that could cause this problem to occur, but I am currently unable to reproduce it.

**Comment by DIYgod** [comment]
I can easily reproduce this on my end. The key point is to start deleting the second when the first deletion is in progress, but my computer screen recording is very slow, which makes it impossible to record this operation. I tried a few times and gave up :(

**Comment by Innei** [comment]
> I can easily reproduce this on my end. The key point is to start deleting the second when the first deletion is in progress, but my computer screen recording is very slow, which makes it impossible

https://user-images.githubusercontent.com/41265413/230722787-87b8bcf5-4cf2-4b21-894b-39cb7bff8c8c.mov

Unable to reproduce

**Comment by DIYgod** [comment]
I found the problem, it may be a bit complicated.

First, let me explain the background:

1. The updating data speed of Crossbell API is often faster than MetaMask, which may result in the situation where MetaMask has not finished yet but the API data has already been updated.

2. Data will be refreshed every time after deletion.

In this case, if one deletion finishes first and then refreshes the data, this time we will get the latest data that both articles have been deleted. As a result, another article that is still being deleted will be removed from the list. Since the component does not perform unmount processing, it will cause an eternal prompt for deletion in progress.

It would be easier to reproduce if the cause is found. There's no need to delete both articles at the same time, just delete one and switch pages.

The solution is to add an unmount processing function. I have written it here.

https://github.com/Crossbell-Box/xLog/commit/9ebc9f3de05a3c6e3e467d6c39dc71232d73433a#diff-150ba7f34fc715eaad916a1a14891f4a2f6621ecb5d5f0f93cbb10e898710950R158

**Pull request merged**
