### PR TITLE
fix: can not remove banner

### PR DESCRIPTION
**Pull request by hyoban**
### WHAT

copilot:summary

copilot:poem

### HOW

copilot:walkthrough

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by DIYgod** [comment]
This method only allows partial fields to be passed in to modify the metadata, so not passing in a banner does not necessarily mean deleting it in many cases.

**Comment by hyoban** [comment]
> This method only allows partial fields to be passed in to modify the metadata, so not passing in a banner does not necessarily mean deleting it in many cases.

Allow passing in `null` to indicate deletion?

**Comment by hyoban** [comment]
@DIYgod updated

**Comment by DIYgod** [comment]
Thanks so much!

**Pull request merged**
