### PR TITLE
fix: query data cannot be undefined. Please make sure to return a val…

### PR DESCRIPTION
**Pull request by jokereven**
…ue other than undefined from your query function

### <samp>🤖 Generated by Copilot at 32aaf36</samp>

Fixed `getSite` function to return null for invalid site ids. This prevents errors and inconsistencies when querying non-existent sites.

### <samp>🤖 Generated by Copilot at 32aaf36</samp>

> _`getSite` returns_
> _null for missing site id_
> _autumn leaves fall_

### WHY

when i open http://rss3.localhost:2222/RSS3-Weekly-Update-July-31--Aug-07-Y23CW29 in dev mode i get one warn, [Query data cannot be undefined. Please make sure to return a value other than undefined from your query function](https://stackoverflow.com/questions/75163140/query-data-cannot-be-undefined-please-make-sure-to-return-a-value-other-than-un);

### <samp>🤖 Generated by Copilot at 32aaf36</samp>

*  Handle non-existent site id in `getSite` function by returning null ([link](https://github.com/Crossbell-Box/xLog/pull/893/files?diff=unified&w=0#diff-8db5e50556c7105744e774aa64e610078c43b9a84d4e2d39bc7fcdaca85d6760R18))

### CLAIM REWARDS

For first-time contributors, please leave your xLog address and Discord ID below to claim your rewards.

### CODE REVIEW

**Comment by DIYgod** [comment]
Thanks, but there are some type errors.

**Comment by jokereven** [comment]
when i delete return null, the problem have disappear, but have that: app-index.js:31 Warning: Prop `id` did not match. Server: "headlessui-switch-:R36r9cmcq:" Client: "headlessui-switch-:Rcrd5ipj9:", https://github.com/tailwindlabs/headlessui/issues/2606 that

**Comment by jokereven** [comment]
> when i delete return null, the problem have disappear, but have that: app-index.js:31 Warning: Prop `id` did not match. Server: "headlessui-switch-:R36r9cmcq:" Client: "headlessui-switch-:Rcrd5ipj9:", [tailwindlabs/headlessui#2606](https://github.com/tailwindlabs/headlessui/issues/2606) that

so i have down next version

**Comment by DIYgod** [comment]
You downgraded Next.js. 🥲

**Comment by jokereven** [comment]
> You downgraded Next.js. 🥲

If it is not allowed, I will close the PR

**Comment by DIYgod** [comment]
Downgrading is not a good solution. Next.js has already fixed this issue in the latest version, but it has introduced other problems, which makes it impossible to update now. I prefer to wait for Next.js to continue their fixes.

**Comment by jokereven** [comment]
okay, thanks.

**Pull request closed without merging**
